account/urls.py
from django.urls import path

from . import views

app_name = 'account'
urlpatterns = [
    path(
        'registrar/',
        views.UsuarioCriarView.as_view(),
        name='registrar'
    ),
    path(
        'login/',
        views.UsuarioLoginView.as_view(),
        name='login'
    ),
    path(
        'logout/',
        views.UsuarioLogoutView.as_view(),
        name='logout'
    )
]

tasks/urls.py
from django.urls import path
from . import views


app_name = 'tasks'
urlpatterns = [
    path('', views.BaseTemplateView.as_view(), name='home'),
    path('tarefa/cadastrar/', views.TarefaCriarView.as_view(), name='cadastrar'),
    path('tarefa/listar/', views.TarefaListarView.as_view(), name='listar'),
    path('tarefa/atualizar/<int:pk>/', views.TarefaAtualizarView.as_view(), name='atualizar'),
    path('tarefa/deletar/<int:pk>/', views.TarefaDeletarView.as_view(), name='deletar'),
]

todo_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('account/', include('account.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/models.py
from django.db import models
from django.contrib.auth.models import User


class Base(models.Model):

    criado = models.DateField(verbose_name='Criado', auto_now_add=True)
    atualizado = models.DateTimeField(verbose_name='Atualizado', auto_now=True)
    ativo = models.BooleanField(verbose_name='Ativo', default=True)

    class Meta:
        abstract = True


class Task(Base):

    class Status(models.TextChoices):
        PENDENTE = 'pendente', 'Pendente'
        EM_ANDAMENTO = 'em_andamento', 'Em andamento'
        CONCLUIDA = 'concluida', 'Concluída'

    usuario = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Usuário'
    )

    titulo = models.CharField(
        verbose_name='Título',
        max_length=100
        )
    descricao = models.TextField(
        verbose_name='Descrição',
        blank=True,
        null=True
        )
    status = models.CharField(
        verbose_name='Status',
        choices=Status.choices,
        default=Status.PENDENTE,
        max_length=20
        )

    class Meta:
        verbose_name = 'Task'
        verbose_name_plural = 'Tasks'

    def __str__(self):
        return f'{self.titulo}'

tasks/forms.py
from django.forms import ModelForm
from django import forms

from .models import Task


class TaskModelForm(ModelForm):

    class Meta:
        model = Task
        fields = ['titulo', 'descricao', 'status']
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'descricao': forms.Textarea(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'})
        }

    def __init__(self, *args, **kwargs):
        self.usuario = kwargs.pop('usuario', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):

        tarefa = super().save(commit=False)

        if self.usuario is not None:

            tarefa.usuario = self.usuario

        if commit:

            tarefa.save()

        return tarefa

tasks/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    TemplateView,
    CreateView,
    ListView,
    UpdateView,
    DeleteView
)

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from .forms import TaskModelForm

from .models import Task
from .utils.mixins import TaskPermissionMixin


class BaseTemplateView(
    LoginRequiredMixin,
    TemplateView
):
    template_name = 'base.html'


class TarefaCriarView(
    LoginRequiredMixin,
    CreateView
):
    template_name = 'tasks/form_add.html'
    form_class = TaskModelForm
    success_url = reverse_lazy('tasks:listar')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

        usuario = self.request.user

        kwargs['usuario'] = usuario

        return kwargs

    def form_valid(self, form):

        messages.success(
            self.request,
            f'Tarefa {form.instance.titulo} adicionado com sucesso.'
        )

        return super().form_valid(form)

    def form_invalid(self, form):

        messages.error(
            self.request,
            'Erro ao adicionar uma nova tarefa. Confira os campos.'
        )

        return super().form_invalid(form)


class TarefaListarView(
    LoginRequiredMixin,
    ListView
):
    template_name = 'tasks/list.html'
    queryset = Task.objects.all()
    context_object_name = 'tasks'

    def get_usuario(self):

        usuario = self.request.user

        return usuario

    def get_queryset(self):

        queryset = super().get_queryset()

        usuario = self.get_usuario()

        queryset = queryset.filter(
            usuario=usuario
        )

        return queryset


class TarefaAtualizarView(
    LoginRequiredMixin,
    TaskPermissionMixin,
    UpdateView
):
    template_name = 'tasks/form_update.html'
    model = Task
    form_class = TaskModelForm
    context_object_name = 'task'
    success_url = reverse_lazy('tasks:listar')

    def form_valid(self, form):

        messages.success(
            self.request,
            'Tarefa atualizada com sucesso.'
        )

        return super().form_valid(form)

    def form_invalid(self, form):

        messages.error(
            self.request,
            'Erro ao tentar atualizar os dados da tarefa. Confira os campos.'
        )

        return super().form_invalid(form)


class TarefaDeletarView(
    LoginRequiredMixin,
    TaskPermissionMixin,
    DeleteView
):
    template_name = 'tasks/form_delete.html'
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('tasks:listar')

tasks/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'tasks/css/base.css' %}">

    <title>{% block title %}Home{% endblock %}</title>
    {% block head %}{% endblock %}
</head>
<body>

    <header class="header">
        <nav class="header-navegacao">
            <ul class="menu-interacao">
                <li>
                    <a 
                        class="header-navegacao-link" 
                        href="{% url 'tasks:home' %}"
                    >
                        Home
                    </a>
                </li>
                <li>
                    <a 
                        class="header-navegacao-link" 
                        href="{% url 'tasks:cadastrar' %}"
                    >
                        Cadastrar tarefa
                    </a>
                </li>
                <li>
                    <a 
                        class="header-navegacao-link" 
                        href="{% url 'tasks:listar' %}"
                    >
                        Lista de tarefas
                    </a>
                </li>
            </ul>

            <ul class="nav-autenticacao">
                {% if user.is_authenticated %}
                    <li>
                        <a 
                            class="header-navegacao-link logout"
                            href="{% url 'account:logout' %}"
                        >
                            Logout
                        </a>
                    </li>
                {% endif %}

            </ul>
        </nav>
    </header>
   

    <main class="container">

        {% if messages  %}
            <div class="espaco-messages">
    
                {% for message in messages %}
                    <p class="{{ message.tags }}"> 
                        {{ message }}
                    </p>
                {% endfor %}
        
            </div>
        {% endif %}


        {% block main %}
        
        
        {% endblock %}
    </main>

    <footer class="rodape">
        Sistema desenvolvido pelo Erick Almeida
    </footer>

    {% block scripts %}{% endblock %}
</body>
</html>